openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Bank'
  description: 'Store you money'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Authentification
    description: Allow signin
  - name: Registration
    description: Allow signup
paths:
  /api/auth/signin:
    post:
      operationId: signIn
      tags:
        - Authentification
      summary: Sign In
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailPasswordDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
  /api/auth/signup:
    get:
      tags:
        - Registration
      summary: Sign Up
      responses:
        '200':
          description: OK

components:
  schemas:
    EmailPasswordDto:
      type: object
      description: email / password
      properties:
        email:
          type: string
          description: e-mail
        password:
          type: string
          description: password