openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Bank'
  description: 'Store you money'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Authentification
    description: Allow signin
  - name: Registration
    description: Allow signup
paths:
  /api/auth/signin:
    post:
      operationId: signIn
      tags:
        - authentification
      summary: Sign In
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailPasswordDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDto'
  /api/auth/signup:
    post:
      tags:
        - registration
      summary: Sign Up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDto'

components:
  schemas:
    EmailPasswordDto:
      type: object
      description: email / password
      properties:
        email:
          type: string
          description: e-mail
        password:
          type: string
          description: password
    ClientDto:
      type: object
      description: client info
      properties:
        email:
          type: string
          description: e-mail
        passwd:
          type: string
          description: passwd
        first-name:
          type: string
          description: first-name
        middle-name:
          type: string
          description: middle-name
        last-name:
          type: string
          description: last-name
        birthday:
          type: string
          description: birthday
        address:
          type: string
          description: address
        phone:
          type: string
          description: phone