-- CREATE TABLE client (
--     id NUMBER GENERATED BY DEFAULT AS IDENTITY,
--     first_name VARCHAR(50) not null,
--     second_name VARCHAR(50) not null,
--     last_name VARCHAR(50) not null,
--     primary key (id)
--     TODO password not null
--     TODO Birthday timestamp not null
--     TODO address not null
--     TODO number not null
--     TODO email(320)
-- );
-- create index idx_client_full_name on client (first_name, second_name, last_name);
-- TODO create index birthday

-- CREATE TABLE account (
--   id number generated by default as identity,
--   client_id number not null,
--   account number not null,
--   date_open timestamp not null,
-- --TODO date_close timestamp,
--   foreign key (client_id) references client(id),
--   primary key (id)
-- );
create index idx_account_account on account (account);

